
CONSENT_FORM = """
**Project:** Measuring Engagement of Text-to-image Generation Models

**Purpose of Study / Aim:** This study aims to understand human preferences in evaluating image engagement for marketing and social media content. We are conducting research to validate an AI model's ability to predict which images are more engaging to viewers. Your participation will help improve automated systems for generating and evaluating marketing imagery.

**Task:** I understand that I will be asked to fill a survey questionnaire. I will be asked basic questions around my advertisement consumption. I will be shown similar images generated by different text-to-image models. I have to select/rank the images based on their visual appeal and engagement, as per my preference.

**Effort:** The survey contains 60 questions. The estimated time required to complete the survey is 10 minutes.

**Benefits:** My participation will help advance understanding of automated systems to evaluate image engagement.

**Voluntary participation:** I understand that my participation is strictly voluntary and anonymous.

**Risks:** I understand that there are no major risks, or feelings of discomfort I would experience when taking part in the study, as it involves only filling responses to they survey questionnaire.

**Confidentiality:** I understand the survey is anonymous. Only the responses to questions will be collected and stored. The data collected will be kept confidential, under the supervision and responsibility of PIs. Only aggregated statistics will be reported in a scientific paper as a result of this study. No personally identifiable information will be used in the publication/dissemination of the results.

**Contact Details:** For further details about the research and how your responses will be used, please contact any of the following people:
- [Varun Khurana](mailto:varun19124@iiitd.ac.in)
- [Yaman Kumar](mailto:yamank@iiitd.ac.in)

**Consent:** Please provide consent to proceed with the survey.
"""


handle_list = ['CHANEL', 'adidasUK', 'gucci', 'MichaelKors', 'RalphLauren', 'Burberry', 'Prada', 'TommyHilfiger', 'Coach', 'PUMA', 'PUMAGolf', 'Reebok', 'Bulgariofficial', 'UrbanOutfitters', 'GameStop', 'footlocker', 'Walmart', 'PetSmart', 'Flipkart', 'nokia', 'Sony', 'Lenovo', 'Dell', 'SamsungMobile', 'htcvive', 'BlackBerry', 'LGUS', 'PorscheNewsroom', 'KTM_Racing', 'Peugeot', 'Toyota', 'GM', 'emirates', 'CruiseNorwegian', 'lufthansa', 'united', 'redlobster', 'Starbucks', 'StarbucksIndia', 'Chilis', 'Sephora', 'revlon', 'avonworldwide', 'TheBodyShopUK', 'Unilever', 'AMCTheatres', 'JohnDeere', 'Vestas', 'USAA']

brands_list = ['CHANEL', 'ADIDAS', 'GUCCI', 'MICHAEL KORS', 'RALPH LAUREN', 'BURBERRY', 'PRADA', 'TOMMY HILFIGER', 'COACH', 'PUMA', 'REEBOK', 'BULGARI', 'URBAN OUTFITTERS', 'GAMESTOP', 'FOOT LOCKER', 'WALMART', 'PETSMART', 'FLIPKART', 'NOKIA', 'SONY', 'LENOVO', 'DELL', 'SAMSUNG', 'HTC', 'BLACKBERRY', 'LG ELECTRONICS', 'PORSCHE', 'RED BULL', 'PEUGEOT', 'TOYOTA', 'GENERAL MOTORS', 'EMIRATES', 'NORWEGIAN', 'LUFTHANSA', 'UNITED AIRLINES', 'RED LOBSTER', 'STARBUCKS', 'CHILIS', 'SEPHORA', 'REVLON', 'AVON', 'THE BODY SHOP', 'UNILEVER', 'AMC', 'JOHN DEERE', 'WIND', 'USAA']

