
CONSENT_FORM = """
#### CONSENT FORM
1. **Project:** Measuring Engagement of Text-to-image Generation Models
2. **Researchers:**
- PI: Dr. Rajiv Ratn Shah (rajivratn@iiitd.ac.in)
- Yaman Kumar (yamank@iiitd.ac.in)
- Varun Khurana (varun19124@iiitd.ac.in)
3. **Purpose of Study / Aim:** This study aims to understand human preferences in evaluating image engagement for marketing and social media content. We are conducting research to validate an AI model's ability to predict which images are more engaging to viewers. Your participation will help improve automated systems for generating and evaluating marketing imagery.
4. **Task:** I understand that I will be asked to fill a survey questionnaire. I will be shown similar images generated by different text-to-image models. I have to select/rank the images based on their visual appeal and engagement, as per my preference. At the end, I will be asked basic questions around your social media consumption.
5. **Effort:** The survey contains 60 questions. The estimated time required to complete the survey is 10-15 minutes.
6. **Benefits:** My participation will help advance understanding of automated systems to evaluate image engagement.
7. **Voluntary participation:** I understand that my participation is strictly voluntary and anonymous.
8. **Risks:** I understand that there are no major risks, or feelings of discomfort I would experience
when taking part in the study, as it involves only filling responses to they survey questionnaire.
9. **Confidentiality:** I understand that the data collected will be kept confidential and only accessible to the researchers affiliated with IIIT-D, under the supervision and responsibility of PIs. I give consent to the researchers to present this work in written and/or other forms for teaching or presentations to advance the knowledge of science and/or academia. Only aggregated statistics will be reported in a scientific paper as a result of this study. No personally identifiable information will be used in the publication/dissemination of the results. The data collected in this study will not be shared with any commercial entities without explicit authorization.
10. **Contact Details:** For further details about this study, please contact any of the following people:
- PI: Dr. Rajiv Ratn Shah (rajivratn@iiitd.ac.in)
- Yaman Kumar (yamank@iiitd.ac.in)
- Varun Khurana (varun19124@iiitd.ac.in)
11. **Approval:** This study has been approved by the Institutional Review Board (IRB), IIIT-D.
12. **For any questions about your rights as a research participant, our objections to the study, you may contact:** IRB Chairperson, Indraprastha Institute of Information Technology, Delhi |Email: IRB@IIITD.AC.in .
13. **CONSENT:**
Please provide consent to proceed with the survey.
"""

brands_list = ['CHANEL', 'adidasUK', 'gucci', 'MichaelKors', 'RalphLauren', 'Burberry', 'Prada', 'TommyHilfiger', 'Coach', 'PUMA', 'PUMAGolf', 'Reebok', 'Bulgariofficial', 'UrbanOutfitters', 'GameStop', 'footlocker', 'Walmart', 'PetSmart', 'Flipkart', 'nokia', 'Sony', 'Lenovo', 'Dell', 'SamsungMobile', 'htcvive', 'BlackBerry', 'LGUS', 'PorscheNewsroom', 'KTM_Racing', 'Peugeot', 'Toyota', 'GM', 'emirates', 'CruiseNorwegian', 'lufthansa', 'united', 'redlobster', 'Starbucks', 'StarbucksIndia', 'Chilis', 'Sephora', 'revlon', 'avonworldwide', 'TheBodyShopUK', 'Unilever', 'AMCTheatres', 'JohnDeere', 'Vestas', 'USAA']

